# TODO: change to check if existingSecret_dbPass is defined
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-pass
type: Opaque
stringData:
  postgres-pass: {{ .Values.backend.cloudbeaver_db_password }}