---
{{- if eq "https" .Values.httpScheme }}
  # TODO: change this to check if existingSecret_ingressTLS is defined
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-ingress-tls--example
data:
  tls.crt: |-
        {{- $chainCertPath := print ( .Values.httpsCertPath ) "/fullchain.pem" }}
        {{ .Files.Get  $chainCertPath | b64enc }}
  tls.key: |-
        {{- $keyCertPath := print ( .Values.httpsCertPath ) "/privkey.pem" }}
        {{ .Files.Get $keyCertPath | b64enc }}
{{- end }}