  # TODO: change this to check if existingSecret_secretSSL is defined
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-secret-ssl--example
data:
  tls.crt: |-
        {{- $chainCertPath := print ( .Values.secretCertPath ) "/cert.crt" }}
        {{ .Files.Get  $chainCertPath | b64enc }}
  tls.key: |-
        {{- $keyCertPath := print ( .Values.secretCertPath ) "/key.key" }}
        {{ .Files.Get $keyCertPath | b64enc }}