apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudbeaver-tm
  name: cloudbeaver-tm
spec:
  replicas: {{ .Values.cloudbeaverTM.replicaCount }}
  selector:
    matchLabels:
      app: cloudbeaver-tm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # date: "{{ now | unixEpoch }}"    # this will likely cause gitops (in our case, flux-cd) to continuously update the deployment. If we interpret the intent of this, we may want to add checksum for configs to force redeployment (which is a bit more stable)
        {{ .Release.Name }}-net: "true"
        {{ .Release.Name }}-private-net: "true"
        app: cloudbeaver-tm
    spec:
      # securityContext:
      #     runAsUser: 1000
      #     runAsGroup: 1000
      #     fsGroup: 1000
      #     fsGroupChangePolicy: "Always"
      containers:
        - image: "{{ .Values.cloudbeaverTM.image }}:{{ .Values.cloudbeaver.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.cloudbeaver.pullPolicy }}"
          name: cloudbeaver-tm
          env:
            - name: CLOUDBEAVER_DC_SERVER_URL
              value: "http://cloudbeaver-dc:8970/dc"
          ports:
            - containerPort: 8973
          resources: {}
          volumeMounts:
            - mountPath: /opt/task-manager/workspace
              name: {{ .Release.Name }}-tm-data
            - name: cross-ssl-cert
              mountPath: /opt/task-manager/conf/certificates
              readOnly: true
      {{- if .Values.cloudbeaver.pullCredsName }}
      imagePullSecrets:
        - name: {{ .Values.cloudbeaver.pullCredsName }}
      {{- end }}
      hostname: cloudbeaver-tm
      restartPolicy: Always
      volumes:
        - name: {{ .Release.Name }}-tm-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tm-data
        - name: cross-ssl-cert
          secret:
            # TODO: change to use existingSecret_crossServiceSSL if defined
            secretName: {{ .Release.Name }}-crossservice-ssl
            items:
              - key: tls.crt
                path: dc-cert.crt