apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-dc-data
  name: {{ .Release.Name }}-dc-data
spec:
  accessModes:
    - ReadWriteMany
  {{- if or (eq .Values.cloudProvider "gcp") (eq .Values.cloudProvider "aws") (eq .Values.cloudProvider "azure") }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- else }}
    {{- if .Values.cloudbeaverDC.storageClassName }}
  # adding support for custom storage class (independent of whether we declare we are in a specific cloud or not)
  storageClassName: {{ .Values.cloudbeaverDC.storageClassName }}
    {{- else }}
      {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
      {{- end }}
    {{- end }}
  {{- end }}
  resources:
    requests:
      storage: 2Gi
status: {}
